apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-role
rules:
- apiGroups:
  - networkextension.bkbcs.tencent.com
  - batch
  resources:
  - ingresses
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - tkex.tencent.com
  resources:
  - gamestatefulsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  - "extensions"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - leases
  - configmaps
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: bcs-ingress-controller
  name: {{ .Release.Name }}-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: bcs-ingress-controller
  name: {{ .Release.Name }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-account
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-role
