//go:build !ignore_autogenerated
// +build !ignore_autogenerated



// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&GameStatefulSet{}, func(obj interface{}) { SetObjectDefaults_GameStatefulSet(obj.(*GameStatefulSet)) })
	scheme.AddTypeDefaultingFunc(&GameStatefulSetList{}, func(obj interface{}) { SetObjectDefaults_GameStatefulSetList(obj.(*GameStatefulSetList)) })
	scheme.AddTypeDefaultingFunc(&GameDeployment{}, func(obj interface{}) { SetObjectDefaults_GameDeployment(obj.(*GameDeployment)) })
	scheme.AddTypeDefaultingFunc(&GameDeploymentList{}, func(obj interface{}) { SetObjectDefaults_GameDeploymentList(obj.(*GameDeploymentList)) })
	return nil
}

func SetObjectDefaults_GameStatefulSet(in *GameStatefulSet) {
	SetDefaults_GameStatefulSet(in)
}

func SetObjectDefaults_GameStatefulSetList(in *GameStatefulSetList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_GameStatefulSet(a)
	}
}

func SetObjectDefaults_GameDeployment(in *GameDeployment) {
	SetDefaults_GameDeployment(in)
}

func SetObjectDefaults_GameDeploymentList(in *GameDeploymentList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_GameDeployment(a)
	}
}
