apiVersion: tkex.tencent.com/v1alpha1
kind: GameDeployment
metadata:
  name: test-gamedeployment
  labels:
    app: test-gd1
spec:
  replicas: 8
  selector:
    matchLabels:
      app: test-gd1
  updateStrategy:
    type: HotPatchUpdate
    partition: 3
    maxUnavailable: 2
  template:
    metadata:
      labels:
        app: test-gd1
    spec:
      containers:
        - name: main
          image: main:v1
          imagePullPolicy: IfNotPresent
          command: ['/main']
          ports:
            - name: http
              containerPort: 8300