apiVersion: tkex.tencent.com/v1alpha1
kind: GameDeployment
metadata:
  name: test-gamedeployment
  labels:
    app: test-gamedeployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: test-gamedeployment
  template:
    metadata:
      labels:
        app: test-gamedeployment
    spec:
      containers:
        - name: python
          image: python:3.5
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["-m", "http.server", "8000" ]
          ports:
            - name: http
              containerPort: 8000
  updateStrategy:
    type: InplaceUpdate
    partition: 3
    maxUnavailable: 2
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 30