

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/Tencent/bk-bcs/bcs-runtime/bcs-mesos/kubebkbcsv2/client/clientset/versioned/typed/monitor/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMonitorV1 struct {
	*testing.Fake
}

func (c *FakeMonitorV1) ServiceMonitors(namespace string) v1.ServiceMonitorInterface {
	return &FakeServiceMonitors{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMonitorV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
