apiVersion: v1 # apiVersion is related to the cluster version
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    release: po
spec:
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: metric
      protocol: TCP
      port: 8080
      targetPort: {{ .Values.env.BK_BCS_cloudNetagentMetricPort }}