---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gamestatefulset-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/status
  - secrets
  - services
  - configmaps
  - endpoints
  - events
  - statefulsets
  - persistentvolumeclaims
  - nodes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups: ["apps"]
  resources: ["controllerrevisions"]
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups: ["tkex.tencent.com"]
  resources:
  - gamestatefulsets
  - gamestatefulsets/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups: ["tkex.tencent.com"]
  resources:
  - hooktemplates
  verbs:
  - get
  - list
  - watch
- apiGroups: ["tkex.tencent.com"]
  resources:
  - hookruns
  verbs:
  - get
  - list
  - create
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: gamestatefulset-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gamestatefulset-operator
subjects:
  - kind: ServiceAccount
    name: gamestatefulset-operator
    namespace: {{ .Release.Namespace }}
