

package models

import "time"

const (
	// PermBackendTypeDefault ..
	PermBackendTypeDefault = iota + 1
	// PermBackendTypeSyncOnce ..
	PermBackendTypeSyncOnce

	// ClusterPermNameView ..
	ClusterPermNameView = "view"
	// ClusterPermNameEdit ..
	ClusterPermNameEdit = "edit"
)

// UserClusterPermission stores the user cluster permission
type UserClusterPermission struct {
	ID uint `gorm:"primary_key"`
	// Backend is where this permission comes from:
	//   - default: this permission was generated by bke itself
	//   - sync_once: this permission was synced from other sources, one cluster at a time
	//
	// The same user+cluster pair can have multiple perm records with different backends, the final permission check
	// result will be caculated by the priority of different backends.
	Backend   int    `gorm:"unique_index:idx_backend_user_cluster_id_name;default:1;"`
	UserID    uint   `gorm:"unique_index:idx_backend_user_cluster_id_name"`
	ClusterID string `gorm:"unique_index:idx_backend_user_cluster_id_name"`
	Name      string `gorm:"unique_index:idx_backend_user_cluster_id_name;size:16"`
	// IsActive means if this permission is valid, the user does not have this permission when it's false,
	// this field's purpose is to record the permission synchronize procedure even if the result is false
	IsActive  bool
	UpdatedAt time.Time
	CreatedAt time.Time
}
