apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.pravega.io
spec:
  group: zookeeper.pravega.io
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeperclusters
    singular: zookeepercluster
    shortNames:
      - zk
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of ZooKeeper servers in the ensemble
      JSONPath: .spec.replicas
    - name: Ready Replicas
      type: integer
      description: The number of ZooKeeper servers in the ensemble that are in a Ready state
      JSONPath: .status.readyReplicas
    - name: Internal Endpoint
      type: string
      description: Client endpoint internal to cluster network
      JSONPath: .status.internalClientEndpoint
    - name: External Endpoint
      type: string
      description: Client endpoint external to cluster network via LoadBalancer
      JSONPath: .status.externalClientEndpoint
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator
rules:
  - apiGroups:
      - zookeeper.pravega.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator-role-binding
subjects:
  - kind: ServiceAccount
    name: zookeeper-operator
    namespace: default
roleRef:
  kind: Role
  name: zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-operator
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
        - name: zookeeper-operator
          # Replace this with the built image name
          image: xxxxxxxxx:8080/paas/bcs/pravega/zookeeper-operator:0.2.7
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - zookeeper-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zookeeper-operator"
      imagePullSecrets:
        - name: dockersecret
---
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: default
spec:
  # Add fields here
  replicas: 3
  image:
    repository: xxxxxxxxxxx:8080/paas/public/pravega/zookeeper
    tag: 0.2.7
  persistence:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "cbs"
    reclaimPolicy: Delete
    resources:
      requests:
        storage: 10Gi