apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # 称必须与下面的spec字段匹配，格式为: <plural>.<group>
  name: meshclusters.mesh.bkbcs.tencent.com
spec:
  # 用于REST API的组名称: /apis/<group>/<version>
  group: mesh.bkbcs.tencent.com
  versions:
    - name: v1
      # 每个版本都可以通过服务标志启用/禁用。
      served: true
      # 必须将一个且只有一个版本标记为存储版本。
      storage: true
  scope: Namespaced  # 指定crd资源作用范围在命名空间或集群
  names:
    # URL中使用的复数名称: /apis/<group>/<version>/<plural>
    plural: meshclusters
    kind: MeshCluster
    listKind: MeshClusterList