# Default values for bcs-k8s-custom-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# work mode for bcs-k8s-custom-scheduler, [netservice, cloudnetservice]
workMode: cloudnetservice

options:
  # cluster id
  cluster: ""
  # the pod annotation key which custom scheduler cares about
  cniAnnotationKey: "tke.cloud.tencent.com/networks"
  # the pod annotation value which custom scheduler cares about
  cniAnnotationValue: "bcs-eni-cni"
  # the pod annotation key for fixed ip schedule
  fixedIPAnnotationKey: "eni.cloud.bkbcs.tencent.com"
  # the pod annotation value for fixed ip schedule
  fixedIPAnnotationValue: "fixed"
  # server ca file path
  caFile: ""
  # server cert file path
  serverCertFile: ""
  # server key file path
  serverKeyFile: ""


netserviceOptions:
  # bcs zookeeper addresses
  bcsZkHosts: ""

cloudNetserviceOptions:
  # cloud netservice endpoints
  cloudNetserviceEndpoints: "bcs-cloud-netservice.bcs-system:80"
  # cloud netservice ca file path
  cloudNetserviceCaFile: ""
  # cloud netservice client cert file path
  cloudNetserviceCertFile: ""
  # cloud netservice client key file path
  cloudNetserviceKeyFile: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
