kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bcs-webhook-server
subjects:
  - kind: ServiceAccount
    name: bcs-webhook-server
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: bcs-webhook-server
  apiGroup: rbac.authorization.k8s.io