apiVersion: v1
kind: Service
metadata:
  name: bcs-webhook-server
  namespace: kube-system
  labels:
    app: bcs-webhook-server
spec:
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: bcs-webhook-server
