apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcs-federated-apiserver.fullname" . }}
  namespace: bcs-system
  labels:
    {{- include "bcs-federated-apiserver.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    {{- include "bcs-federated-apiserver.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bcs-federated-apiserver.fullname" . }}
  namespace: bcs-system
  labels:
    {{- include "bcs-federated-apiserver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bcs-federated-apiserver.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "bcs-federated-apiserver.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: bcs-federated-apiserver
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: bcs-federated-apiserver
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./bcs-federated-apiserver"
        args:
        - "--etcd-servers=http://bcs-federated-apiserver-etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: apiserver-certs
        secret:
          secretName: bcs-federated-apiserver
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "bcs-federated-apiserver.fullname" . }}
  namespace: bcs-system
  labels:
    {{- include "bcs-federated-apiserver.labels" . | nindent 4 }}
data:
  tls.crt: "{{ .Values.secret.tlsCrt }}"
  tls.key: "{{ .Values.secret.tlsKey }}"
