apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.etcd.name }}
  namespace: bcs-system
  labels:
    {{- include "bcs-federated-apiserver-etcd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bcs-federated-apiserver-etcd.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.etcd.svcName }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "bcs-federated-apiserver-etcd.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: etcd
          image: "{{ .Values.etcdImage.registry }}/{{ .Values.etcdImage.repository }}:{{ .Values.etcdImage.tag }}"
          imagePullPolicy: {{ .Values.etcdImage.pullPolicy }}
          env:
            - name: ETCD_DATA_DIR
              value: /etcd-data-dir
          command:
            - /usr/local/bin/etcd
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://localhost:2379
          ports:
            - containerPort: 2379
          readinessProbe:
            httpGet:
              port: 2379
              path: /health
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: 2379
              path: /health
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcd.svcName }}
  namespace: bcs-system
  labels:
    {{- include "bcs-federated-apiserver-etcd.labels" . | nindent 4 }}
spec:
  ports:
    - port: 2379
      name: etcd
      targetPort: 2379
  selector:
    {{- include "bcs-federated-apiserver-etcd.selectorLabels" . | nindent 4 }}
