apiVersion: tkex.tencent.com/v1alpha1
kind: HookTemplate
metadata:
  name: test
spec:
  metrics:
    - name: webtest
      count: 2
      interval: 60s
      failureLimit: 0
      successCondition: "asInt(result) < 30"
      provider:
        web:
          url: http://1.1.1.1:9091
          jsonPath: "{$.age}"