apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-clusterrole
rules:
- apiGroups:
  - mesh.bmsf.tencent.com
  resources:
  - appnodes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mesh.bmsf.tencent.com
  resources:
  - appnodes/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - mesh.bmsf.tencent.com
  resources:
  - appsvcs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mesh.bmsf.tencent.com
  resources:
  - appsvcs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - clb.bmsf.tencent.com
  resources:
  - clbingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - clb.bmsf.tencent.com
  resources:
  - clbingresses/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - network.bmsf.tencent.com
  resources:
  - cloudlisteners
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - network.bmsf.tencent.com
  resources:
  - cloudlisteners/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
