apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secretID: "{{ .Values.clbSecretID }}"
  secretKey: "{{ .Values.clbSecretKey }}"