# Default values for bcs-federated-apiserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#wether create namespace bcs-system or not
createNamespace: false

fullnameOverride: "bcs-federated-apiserver"

image:
  registry: "xxxxxxx.xxxxxxx.xxx"
  repository: "yyy/bcs-federated-apiserver"
  pullPolicy: Always

imagePullSecrets: []

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "250m"

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  bcsStorageAddress: "http://x.xxx.xx.xxx:xxxx"
  bcsStoragePodUri: "/xxxxxxxxxx/xx/xxxxxxx/xxxxxxxxxxxxxxx/xxx"
  bcsStorageToken: ""
  memberClusterIgnorePrefix: "xxxxxxx"
  memberClusterOverride: "xxx-xxx-xxxxx"

secret:
  tlsCrt: ""
  tlsKey: ""

etcd:
  name: "bcs-federated-apiserver-etcd"
  svcName: "bcs-federated-apiserver-etcd-svc"

etcdImage:
  registry: "xxxxxxx.xxxxxxx.xxx"
  repository: "yyy/etcd-federated-apiserver"
  tag: "v3.4.13"
  pullPolicy: Always
