apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bcs-gamestatefulset-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-gamestatefulset-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bcs-gamestatefulset-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bcs-gamestatefulset-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "common.images.pullSecrets" ( dict "images" (list .Values) "global" .Values.global) | nindent 6  }}
      serviceAccountName: gamestatefulset-operator
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.pullPolicy | default .Values.image.pullPolicy }}
          command: ["/data/bcs/bcs-gamestatefulset-operator/container-start.sh"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
