# Default values for bcs-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 0.0.1


resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

cloud: tencetcloud

# 腾讯云clb API域名
tencentcloudClbDomain: clb.tencentcloudapi.com
# 腾讯云云区域
tencentcloudRegion: ap-shanghai
# 腾讯云AccessID进行Base64之后的值
tencentcloudSecretID: xxxxxxxxx
# 腾讯云AccessKey进行Base64之后的值
tencentcloudSecretKey: xxxxxxxxxx
