

// Code generated by client-gen. DO NOT EDIT.

package v2

type AdmissionWebhookConfigurationExpansion interface{}

type AgentExpansion interface{}

type AgentSchedInfoExpansion interface{}

type ApplicationExpansion interface{}

type BcsClusterAgentSettingExpansion interface{}

type BcsCommandInfoExpansion interface{}

type BcsConfigMapExpansion interface{}

type BcsDaemonsetExpansion interface{}

type BcsEndpointExpansion interface{}

type BcsSecretExpansion interface{}

type BcsServiceExpansion interface{}

type BcsTransactionExpansion interface{}

type CrdExpansion interface{}

type CrrExpansion interface{}

type DeploymentExpansion interface{}

type FrameworkExpansion interface{}

type TaskExpansion interface{}

type TaskGroupExpansion interface{}

type VersionExpansion interface{}
