# Default values for clb-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# clb-controller镜像名字
image: clb-controller:0.0.1-alpha
imagePullSecrets: []
# clb-controller监听的端口
port: 18484
useHostNetwork: "true"
# clb-controller服务发现的模式，可选kubernetes, custom
serviceRegistry: "kubernetes"
# 后端容器的ip类型，可选overlay, underlay
backendIPType: "underlay"
# 已经存在的clb的名字，或者需要创建的clb的名字
clbName: "xxxxxx-clb"
# clb网络类型，可选private, public
netType: "public"
# 日志级别，推荐填3
v: 3
# clb控制代码的实现方式，可选api, sdk
clbImplement: sdk
# 通过何种方式绑定后端，可选cvm, eni
clbBackendMode: eni
# clb位于的云区域
clbRegion: ap-shanghai
# 腾讯云账户secretID base64码
clbSecretID: xxxxxxxxxxxxxxxxxx
# 腾讯云账户secretKey base64码
clbSecretKey: xxxxxxxxxxxxxxxxxxx
# projectID
clbProjectID: 0
# vpc id
clbVpcID: "xxxxxxxx"
# subnet id, 只需在内网clb模式下使用
#clbSubnetID: "xxxxx"
# 额外的环境变量
env: []