apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bcs-kube-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-kube-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bcs-kube-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bcs-kube-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "common.images.pullSecrets" ( dict "images" (list .Values) "global" .Values.global) | nindent 6  }}
      serviceAccountName: {{ include "bcs-kube-agent.serviceAccountName" . }}
      terminationGracePeriodSeconds: 3
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.pullPolicy | default .Values.image.pullPolicy }}
          args:
            - --bke-address={{ .Values.args.BK_BCS_API }}
            - --cluster-id={{ .Values.global.env.BK_BCS_clusterId | default .Values.args.BK_BCS_clusterId }}
            - --insecureSkipVerify=true
            - --verbosity={{ .Values.global.env.BK_BCS_log_level | default .Values.args.BK_BCS_log_level }}
            {{- if eq .Values.args.BK_BCS_kubeAgentWSTunnel "true" }}
            - --use-websocket={{ .Values.args.BK_BCS_kubeAgentWSTunnel }}
            - --websocket-path={{ .Values.args.BK_BCS_websocketPath }}
            {{- else }}
            - --external-proxy-addresses={{ .Values.args.BK_BCS_kubeAgentProxy }}
            - --report-path={{ .Values.args.BK_BCS_reportPath }}
            {{- end }}
          env:
            - name: USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "bcs-kube-agent.fullname" . }}
                  key: token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
