kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bcs-k8s-custom-scheduler.fullname" . }}-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/binding", "bindings"]
    verbs: ["*"]
  {{- if eq .Values.workMode "cloudnetservice" }}
  - apiGroups: ["cloud.bkbcs.tencent.com"]
    resources: ["cloudips", "nodenetworks"]
    verbs: ["get", "list", "watch"]
  {{- end }}