apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-bcs-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-cluster-init.labels" . | nindent 4 }}
data:
  {{ .Values.key.caCert }}: |
    {{ .Values.certs.caCert | nindent 4 | trim}}
  {{ .Values.key.clientCert }}: |
    {{ .Values.certs.clientCert | nindent 4 | trim}}
  {{ .Values.key.clientKey }}: |
    {{ .Values.certs.clientKey | nindent 4 | trim}}
