{{ if .Values.enabled }}
{{- if .Values.createNamespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-cluster-init.labels" . | nindent 4 }}
{{- end }}
{{ end }}