{{ if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: bk-bcs-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-cluster-init.labels" . | nindent 4 }}
data:
{{- range $path, $_ := $.Files.Glob "cert/bcs*.*" }}
{{ $path | base | indent 2 }}: |-
{{ $.Files.Get $path | b64enc |indent 4 }}
{{- end }}
{{ end }}