apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-webhook-server
  namespace: kube-system
  labels:
    app: bcs-webhook-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bcs-webhook-server
  template:
    metadata:
      labels:
        app: bcs-webhook-server
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: bcs-webhook-server
      containers:
        - name: bcs-webhook-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /data/bcs/bcs-webhook-server/container-start.sh
          args:
            - --address=0.0.0.0
            - --port=443
            - --log_dir=/data/bcs/logs/bcs
            - --log_max_size=500
            - --log_max_num=10
            - --logtostderr=true
            - --alsologtostderr=true
            - --v=3
            - --stderrthreshold=2
            - --server_cert_file={{ .Values.serverCertFile }}
            - --server_key_file={{ .Values.serverKeyFile }}
            - --engine_type=kubernetes
            - --plugin_dir={{ .Values.pluginConfDir }}
            - --plugins={{ .Values.enabledPlugins }}
          ports:
          - name: http
            containerPort: 443
            protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8}}
      {{- end }}

