---
apiVersion: v1
kind: Secret
metadata:
  name: bcs-webhook-server-certs
  namespace: kube-system
type: Opaque
data:
  cert.pem: {{ .Values.serverCert }}
  key.pem: {{ .Values.serverKey }}

{{- if .Values.plugins.dbpriv.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bcs-db-privilege
  namespace: kube-system
type: Opaque
data:
  # go-esb-sdk
  sdk-appCode: {{ .Values.plugins.dbpriv.sdkAppCode }}
  sdk-appSecret: {{ .Values.plugins.dbpriv.sdkAppSecret }}
  sdk-operator: {{ .Values.plugins.dbpriv.sdkOperator }}
{{- end }}