apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clbingresses.clb.bmsf.tencent.com
spec:
  group: clb.bmsf.tencent.com
  names:
    kind: ClbIngress
    plural: clbingresses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            http:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              items:
                properties:
                  clbPort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  healthCheck:
                    properties:
                      enabled:
                        type: boolean
                      healthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                      httpCheckPath:
                        maxLength: 80
                        minLength: 1
                        type: string
                      httpCode:
                        format: int64
                        maximum: 31
                        minimum: 1
                        type: integer
                      intervalTime:
                        format: int64
                        maximum: 300
                        minimum: 5
                        type: integer
                      timeout:
                        format: int64
                        maximum: 60
                        minimum: 2
                        type: integer
                      unHealthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                    type: object
                  host:
                    maxLength: 80
                    minLength: 1
                    type: string
                  lbPolicy:
                    properties:
                      backendWeights:
                        items:
                          properties:
                            labelSelector:
                              type: object
                            weight:
                              format: int64
                              maximum: 100
                              minimum: 0
                              type: integer
                          required:
                          - labelSelector
                          - weight
                          type: object
                        type: array
                      strategy:
                        enum:
                        - wrr
                        - ip_hash
                        - least_conn
                        type: string
                    required:
                    - strategy
                    type: object
                  namespace:
                    type: string
                  path:
                    maxLength: 80
                    minLength: 1
                    type: string
                  serviceName:
                    type: string
                  servicePort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  sessionTime:
                    format: int64
                    maximum: 3600
                    minimum: 30
                    type: integer
                  tls:
                    properties:
                      certCaId:
                        type: string
                      certCilentCaContent:
                        type: string
                      certClientCaName:
                        type: string
                      certId:
                        type: string
                      certServerContent:
                        type: string
                      certServerKey:
                        type: string
                      certServerName:
                        type: string
                      mode:
                        type: string
                    type: object
                required:
                - host
                - path
                - serviceName
                - namespace
                - clbPort
                - servicePort
                type: object
              type: array
            https:
              items:
                properties:
                  clbPort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  healthCheck:
                    properties:
                      enabled:
                        type: boolean
                      healthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                      httpCheckPath:
                        maxLength: 80
                        minLength: 1
                        type: string
                      httpCode:
                        format: int64
                        maximum: 31
                        minimum: 1
                        type: integer
                      intervalTime:
                        format: int64
                        maximum: 300
                        minimum: 5
                        type: integer
                      timeout:
                        format: int64
                        maximum: 60
                        minimum: 2
                        type: integer
                      unHealthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                    type: object
                  host:
                    maxLength: 80
                    minLength: 1
                    type: string
                  lbPolicy:
                    properties:
                      backendWeights:
                        items:
                          properties:
                            labelSelector:
                              type: object
                            weight:
                              format: int64
                              maximum: 100
                              minimum: 0
                              type: integer
                          required:
                          - labelSelector
                          - weight
                          type: object
                        type: array
                      strategy:
                        enum:
                        - wrr
                        - ip_hash
                        - least_conn
                        type: string
                    required:
                    - strategy
                    type: object
                  namespace:
                    type: string
                  path:
                    maxLength: 80
                    minLength: 1
                    type: string
                  serviceName:
                    type: string
                  servicePort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  sessionTime:
                    format: int64
                    maximum: 3600
                    minimum: 30
                    type: integer
                  tls:
                    properties:
                      certCaId:
                        type: string
                      certCilentCaContent:
                        type: string
                      certClientCaName:
                        type: string
                      certId:
                        type: string
                      certServerContent:
                        type: string
                      certServerKey:
                        type: string
                      certServerName:
                        type: string
                      mode:
                        type: string
                    type: object
                required:
                - host
                - path
                - serviceName
                - namespace
                - clbPort
                - servicePort
                type: object
              type: array
            statefulset:
              properties:
                http:
                  items:
                    properties:
                      endIndex:
                        format: int64
                        type: integer
                      startIndex:
                        format: int64
                        type: integer
                      startPort:
                        format: int64
                        type: integer
                    required:
                    - startPort
                    type: object
                  type: array
                https:
                  items:
                    properties:
                      endIndex:
                        format: int64
                        type: integer
                      startIndex:
                        format: int64
                        type: integer
                      startPort:
                        format: int64
                        type: integer
                    required:
                    - startPort
                    type: object
                  type: array
                tcp:
                  items:
                    properties:
                      endIndex:
                        format: int64
                        type: integer
                      startIndex:
                        format: int64
                        type: integer
                      startPort:
                        format: int64
                        type: integer
                    required:
                    - startPort
                    type: object
                  type: array
                udp:
                  items:
                    properties:
                      endIndex:
                        format: int64
                        type: integer
                      startIndex:
                        format: int64
                        type: integer
                      startPort:
                        format: int64
                        type: integer
                    required:
                    - startPort
                    type: object
                  type: array
              type: object
            tcp:
              items:
                properties:
                  clbPort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  healthCheck:
                    properties:
                      enabled:
                        type: boolean
                      healthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                      httpCheckPath:
                        maxLength: 80
                        minLength: 1
                        type: string
                      httpCode:
                        format: int64
                        maximum: 31
                        minimum: 1
                        type: integer
                      intervalTime:
                        format: int64
                        maximum: 300
                        minimum: 5
                        type: integer
                      timeout:
                        format: int64
                        maximum: 60
                        minimum: 2
                        type: integer
                      unHealthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                    type: object
                  lbPolicy:
                    properties:
                      backendWeights:
                        items:
                          properties:
                            labelSelector:
                              type: object
                            weight:
                              format: int64
                              maximum: 100
                              minimum: 0
                              type: integer
                          required:
                          - labelSelector
                          - weight
                          type: object
                        type: array
                      strategy:
                        enum:
                        - wrr
                        - ip_hash
                        - least_conn
                        type: string
                    required:
                    - strategy
                    type: object
                  namespace:
                    type: string
                  serviceName:
                    type: string
                  servicePort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  sessionTime:
                    format: int64
                    maximum: 3600
                    minimum: 30
                    type: integer
                required:
                - serviceName
                - namespace
                - clbPort
                - servicePort
                type: object
              type: array
            udp:
              items:
                properties:
                  clbPort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  healthCheck:
                    properties:
                      enabled:
                        type: boolean
                      healthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                      httpCheckPath:
                        maxLength: 80
                        minLength: 1
                        type: string
                      httpCode:
                        format: int64
                        maximum: 31
                        minimum: 1
                        type: integer
                      intervalTime:
                        format: int64
                        maximum: 300
                        minimum: 5
                        type: integer
                      timeout:
                        format: int64
                        maximum: 60
                        minimum: 2
                        type: integer
                      unHealthNum:
                        format: int64
                        maximum: 10
                        minimum: 2
                        type: integer
                    type: object
                  lbPolicy:
                    properties:
                      backendWeights:
                        items:
                          properties:
                            labelSelector:
                              type: object
                            weight:
                              format: int64
                              maximum: 100
                              minimum: 0
                              type: integer
                          required:
                          - labelSelector
                          - weight
                          type: object
                        type: array
                      strategy:
                        enum:
                        - wrr
                        - ip_hash
                        - least_conn
                        type: string
                    required:
                    - strategy
                    type: object
                  namespace:
                    type: string
                  serviceName:
                    type: string
                  servicePort:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  sessionTime:
                    format: int64
                    maximum: 3600
                    minimum: 30
                    type: integer
                required:
                - serviceName
                - namespace
                - clbPort
                - servicePort
                type: object
              type: array
          type: object
        status:
          properties:
            lastUpdateTime:
              format: date-time
              type: string
            message:
              type: string
            status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          required:
          - status
          - message
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
