apiVersion: apps/v1
kind: Deployment
metadata:
  name: clb-controller-deployment
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: clb-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: clb-controller
    spec:
      serviceAccountName: clb-controller-serviceaccount
      containers:
      - name: clb-controller-con1
        image: "{{CLB_CTRL_IMAGE}}"
        command:
        - /clb/clb-controller
        args:
        - server
        - --port
        - "{{CLB_CTRL_METRIC_PORT}}"
        - --serviceRegistry
        - {{CLB_CTRL_REGISTRY}}
        - --backendIPType
        - {{CLB_CTRL_BACKEND_IP_TYPE}}
        - --clbname
        - {{CLB_NAME}}
        - --netType
        - {{CLB_NET_TYPE}}
        - --v
        - "3"
        env:
        - name: BCS_CLB_IMPLEMENT
          value: {{CLB_IMPLEMENT}}
        - name: BCS_CLB_BACKENDMODE
          value: {{CLB_BACKENDMODE}}
        - name: BCS_CLB_REGION
          value: {{CLB_REGION}}
        - name: BCS_CLB_SECRETID
          value: {{CLB_SECRETID}}
        - name: BCS_CLB_SECRETKEY
          value: {{CLB_SECRETKEY}}
        - name: BCS_CLB_PROJECTID
          value: "{{CLB_PROJECTID}}"
        - name: BCS_CLB_VPCID
          value: "{{CLB_VPCID}}"
        - name: BCS_CLB_SUBNET
          value: "{{CLB_SUBNET}}"
        ports:
        - name: http-metric
          containerPort: {{CLB_CTRL_METRIC_PORT}}
        