apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bcs-kube-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: |
    {{ .Values.args.token | nindent 4 | trim}}