

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ServiceMonitorListerExpansion allows custom methods to be added to
// ServiceMonitorLister.
type ServiceMonitorListerExpansion interface{}

// ServiceMonitorNamespaceListerExpansion allows custom methods to be added to
// ServiceMonitorNamespaceLister.
type ServiceMonitorNamespaceListerExpansion interface{}
